import 'dart:convert';
import 'dart:io';

/// Creates GitHub issues via the logged-in `gh` CLI (no token management
/// needed). Optionally uses [token] (GH_TOKEN) without touching your global
/// gh login.
class GithubTicketer {
  final String repo; // owner/repo
  final String token;
  final Duration timeout;

  GithubTicketer(this.repo,
      {this.token = '', this.timeout = const Duration(seconds: 60)});

  /// Create an issue; returns its URL.
  Future<String> createIssue({
    required String title,
    required String body,
  }) async {
    if (repo.isEmpty) {
      throw Exception('GITHUB_REPO is not set — configure it in Settings.');
    }
    final result = await Process.run(
      'gh',
      ['issue', 'create', '--repo', repo, '--title', title, '--body', body],
      environment: token.isEmpty ? null : {'GH_TOKEN': token},
    ).timeout(timeout);

    if (result.exitCode != 0) {
      throw Exception(
          'gh issue create failed (exit ${result.exitCode}): ${result.stderr}');
    }
    final out = result.stdout.toString();
    final m = RegExp(r'https://github\.com/\S+/issues/\d+').firstMatch(out);
    if (m == null) {
      throw Exception('Issue created but URL not found in output: $out');
    }
    return m.group(0)!;
  }

  /// Compose a GitHub issue title/body from an item (with its AI analysis).
  /// [lang] = 'en' | 'zh-Hant'.
  static ({String title, String body}) compose(Map<String, Object?> r,
      {String lang = 'en'}) {
    final zh = lang == 'zh-Hant';
    final isFeature = (r['source'] ?? 'sentry') == 'feature';
    final shortId = (r['short_id'] ?? '') as String;
    final rawTitle = (r['title'] ?? '') as String;

    String s(Object? v) => (v ?? '').toString();
    final buf = StringBuffer();
    final confidence = r['confidence'] != null
        ? (zh
            ? '　（信心 ${((r['confidence'] as num) * 100).round()}%）'
            : ' (confidence ${((r['confidence'] as num) * 100).round()}%)')
        : '';

    if (isFeature) {
      final title =
          '${zh ? '[需求]' : '[Feature]'} ${_truncate(rawTitle, 70)}';
      if (s(r['detail']).isNotEmpty) buf.writeln('${r['detail']}\n');
      buf.writeln(zh
          ? '**可行性**：${s(r['feasibility'])}　**工作量**：${s(r['effort'])}　**建議優先度**：${s(r['priority_score'])}$confidence\n'
          : '**Feasibility**: ${s(r['feasibility'])} · **Effort**: ${s(r['effort'])} · **Suggested priority**: ${s(r['priority_score'])}$confidence\n');
      _section(buf, zh ? '可行性摘要' : 'Summary', s(r['root_cause_summary']));
      _section(buf, zh ? '影響範圍' : 'Affected areas', s(r['affected_areas']));
      _section(buf, zh ? '建議做法' : 'Approach', s(r['recommended_action']));
      _section(buf, zh ? '風險' : 'Risks', s(r['risks']));
      buf.writeln(zh
          ? '\n---\n_由 sentry-ai-triage 產生（需求）_'
          : '\n---\n_Generated by sentry-ai-triage (feature)_');
      return (title: title, body: buf.toString());
    }

    // Bug
    final title = '[$shortId] ${_truncate(rawTitle, 70)}';
    if (r['severity_score'] != null) {
      buf.writeln(zh
          ? '**嚴重度**：${r['severity_score']}　**可修性**：${s(r['is_app_fixable'])}$confidence'
          : '**Severity**: ${r['severity_score']} · **Fixability**: ${s(r['is_app_fixable'])}$confidence');
    }
    buf.writeln(zh
        ? '**影響**：${s(r['total_count'])} 次 / ${s(r['user_count'])} 人'
        : '**Impact**: ${s(r['total_count'])} events / ${s(r['user_count'])} users');
    buf.writeln('**Sentry**: ${s(r['permalink'])}\n');
    _section(buf, zh ? '根因' : 'Root cause', s(r['root_cause_summary']));
    _section(
        buf, zh ? '建議處置' : 'Recommended action', s(r['recommended_action']));
    buf.writeln(zh
        ? '\n---\n_由 sentry-ai-triage 產生_'
        : '\n---\n_Generated by sentry-ai-triage_');
    return (title: title, body: buf.toString());
  }

  /// Add a comment under an issue (used to auto-@claude and start discussion).
  Future<void> addComment(String issueUrl, String body) async {
    final m = RegExp(r'/issues/(\d+)').firstMatch(issueUrl);
    if (m == null) {
      throw Exception('Cannot parse issue number from URL: $issueUrl');
    }
    final number = m.group(1)!;
    final res = await Process.run(
      'gh',
      ['issue', 'comment', number, '--repo', repo, '--body', body],
      environment: token.isEmpty ? null : {'GH_TOKEN': token},
    ).timeout(timeout);
    if (res.exitCode != 0) {
      throw Exception(
          'gh issue comment failed (exit ${res.exitCode}): ${res.stderr}');
    }
  }

  /// Current state of an issue/PR: open | closed | merged | deleted | unknown.
  Future<String> stateOf(String url) async {
    final isPr = url.contains('/pull/');
    final numMatch = RegExp(r'/(?:issues|pull)/(\d+)').firstMatch(url);
    if (numMatch == null) return 'unknown';
    final number = numMatch.group(1)!;
    final res = await Process.run(
      'gh',
      [isPr ? 'pr' : 'issue', 'view', number, '--repo', repo, '--json', 'state'],
      environment: token.isEmpty ? null : {'GH_TOKEN': token},
    ).timeout(const Duration(seconds: 30));
    if (res.exitCode != 0) {
      final err = res.stderr.toString().toLowerCase();
      if (err.contains('not found') || err.contains('could not resolve')) {
        return 'deleted';
      }
      return 'unknown';
    }
    try {
      final j = jsonDecode(res.stdout.toString()) as Map<String, dynamic>;
      return (j['state'] ?? 'unknown').toString().toLowerCase();
    } catch (_) {
      return 'unknown';
    }
  }

  static void _section(StringBuffer buf, String heading, String content) {
    if (content.trim().isEmpty) return;
    buf.writeln('### $heading\n$content\n');
  }

  static String _truncate(String s, int n) =>
      s.length <= n ? s : '${s.substring(0, n)}…';
}
